### ISSUE TITLE
GitElephant breaks under non-english locales

### ISSUE THREAD

**Issue by axel-rutz** [matteosister/GitElephant#121]
getRemote() throws "Invalid data provided for remote detail parsing".

The debugged data below shows that this boils down to parsing localized (de) git output.
I guess the solution should be to use non-localized output to parse or at least define the locale. 

```
exception 'UnexpectedValueException' with message 'Invalid data provided for remote detail parsing' in                                                                                           [error]
/var/www/virtual/clsysdev/html/panelizer/vendor/cypresslab/gitelephant/src/GitElephant/Objects/Remote.php:204
Stack trace:
#0 /var/www/virtual/clsysdev/html/panelizer/vendor/cypresslab/gitelephant/src/GitElephant/Objects/Remote.php(181): GitElephant\Objects\Remote->parseOutputLines(Array)
#1 /var/www/virtual/clsysdev/html/panelizer/vendor/cypresslab/gitelephant/src/GitElephant/Objects/Remote.php(87): GitElephant\Objects\Remote->createFromCommand(true)
#2 /var/www/virtual/clsysdev/html/panelizer/vendor/cypresslab/gitelephant/src/GitElephant/Objects/Remote.php(104): GitElephant\Objects\Remote->__construct(Object(GitElephant\Repository),
'test', true)
#3 /var/www/virtual/clsysdev/html/panelizer/vendor/cypresslab/gitelephant/src/GitElephant/Repository.php(974): GitElephant\Objects\Remote::pick(Object(GitElephant\Repository), 'test', true)
#4 /var/www/virtual/clsysdev/html/panelizer/drush/deploya/deploya.drush.inc(62): GitElephant\Repository->getRemote('test')
```

Offending $remoteDetails data:
```
Array
(
    [0] => * Remote-Repository test
    [1] =>   URL zum Abholen: ssh://s1888@repo.freistilbox.net/~/site
    [2] =>   URL zum Versenden: ssh://s1888@repo.freistilbox.net/~/site
    [3] =>   Hauptbranch: master
    [4] =>   Remote-Branches:
    [5] =>     deploy neu (wird bei nächstem "fetch" in remotes/test gespeichert)
    [6] =>     master neu (wird bei nächstem "fetch" in remotes/test gespeichert)
)

```

**Comment by axel-rutz** [comment]
The above commit works quite well. I'll report back if i can find any repercussions to it.
